apiVersion: v1
kind: Service
metadata:
  name: spire-proxy-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: spire-proxy
# type:\"k8s\" value:\"sa:default\"  type:\"k8s\" value:\"ns:default\"
# k8s:ns:default