apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
        instance: vault
    spec:
      containers:
        - name: cloudid-vault
          image: cloudid-vault:0.1-SNAPSHOT
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
          - containerPort: 8200
            name: main-port
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8300
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          volumeMounts:
              - name: vault-config
                mountPath: /vault/config
                readOnly: true
              - name: vault-secrets
                mountPath: /vault/secrets
                readOnly: true
              - name: vault-file
                mountPath: /vault/file
              - name: vault-logs
                mountPath: /vault/logs
              - name: shared
                mountPath: /shared
        - name: cloudid-vault-sidecar
          image: cloudid-vault-sidecar:0.1-SNAPSHOT
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
              - name: spire-agent-socket
                mountPath: /spire/socket
                readOnly: false
              - name: shared
                mountPath: /shared
      volumes:
        - name: vault-config
          configMap:
            name: vault-config
            items:
            - key: vault.conf
              path: vault.conf
        - name: vault-secrets
          secret:
            secretName: vault-secrets
        - name: vault-logs
          emptyDir: {}
        - name: vault-file
          emptyDir: {}
        - name: shared
          emptyDir: {}
        - name: spire-agent-socket
          hostPath:
           path: /mnt/spire/agent/socket
