apiVersion: v1
kind: Secret
metadata:
  name: vault-secrets
type: Opaque
data:
  vault.pem: {{VAULT_CERT}}
  vault-key.pem: {{VAULT_KEY}}
  upstream.pem: {{UPSTREAM_CERT}}
  acl_payload.json: {{ACL_PAYLOAD}}
