apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cloudid-server
  labels:
    app: cloudid-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudid-server
  template:
    metadata:
      labels:
        app: cloudid-server
    spec:
      containers:
      - name: cloudid
        image: {{DOCKER_QUALIFIED_NAME}}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
              cpu: 200m
              memory: 512Mi
        volumeMounts:
        - name: application-config
          mountPath: /deployment/config
          readOnly: true
        - name: spire-agent-socket
          mountPath: /spire/socket
          readOnly: false
        - name: demo-secrets
          mountPath: /deployment/secrets
          readOnly: true
        env:
          - name: JAVA_TOOL_OPTIONS
            valueFrom:
              configMapKeyRef:
                name: cloudid-server-config
                key: JAVA_TOOL_OPTIONS
        ports:
        - name: https
          containerPort: 8443
        - name: jvm-debug
          containerPort: 5005
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /actuator/health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 25
          periodSeconds: 60
          timeoutSeconds: 3
      imagePullSecrets:
        # Needs to be defined for this deployment to work
        - name: qaware-artifactory
      volumes:
        - name: application-config
          configMap:
            name: cloudid-server-config
            items:
            - key: application.properties
              path: application.properties
            - key: logback.xml
              path: logback.xml
        - name: spire-agent-socket
          hostPath:
           path: /mnt/spire/agent/socket
        - name: demo-secrets
          secret:
            secretName: demo-secrets