kind: PersistentVolume
apiVersion: v1
metadata:
  name: agent-socket-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/spire-agent"