apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ingress-proxy
  labels:
    app: ingress-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-proxy
  template:
    metadata:
      labels:
        app: ingress-proxy
    spec:
      containers:
      - name: cloudid
        image: {{DOCKER_QUALIFIED_NAME}}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
              cpu: 200m
              memory: 512Mi
        volumeMounts:
        - name: application-config
          mountPath: /deployment/config
          readOnly: true
        - name: spire-agent-socket
          mountPath: /spire/socket
          readOnly: false
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Djavax.net.debug=all"
        ports:
        - name: https
          containerPort: 8443
        - name: jvm-debug
          containerPort: 5005
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /actuator/health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 1
      imagePullSecrets:
        # Needs to be defined for this deployment to work
        - name: qaware-artifactory
      volumes:
        - name: application-config
          configMap:
            name: ingress-proxy-config
            items:
            - key: application.properties
              path: application.properties
        - name: spire-agent-socket
          hostPath:
           path: /mnt/spire/agent/socket