apiVersion: v1
kind: Service
metadata:
  name: spire-proxy
spec:
  type: NodePort
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: spire-proxy
