apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-server-config-front
data:
  application.properties: |
    management.server.port=8081
    logging.level.org.springframework.web=INFO
    app.backend=https://demo-server-service-back.back:444
    app.clientAuth=false
