apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: demo-server-front
  labels:
    app: demo-server-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-server-front
  template:
    metadata:
      labels:
        app: demo-server-front
    spec:
      containers:
      - name: demo-server
        image: {{DOCKER_QUALIFIED_NAME}}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: application-config
          mountPath: /deployment/config
          readOnly: true
        - name: spire-agent-socket
          mountPath: /spire/socket
          readOnly: false
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
        ports:
        - name: https
          containerPort: 8443
        - name: jvm-debug
          containerPort: 5005
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
      imagePullSecrets:
        # Needs to be definied for this deployment to work
        - name: qaware-artifactory
      volumes:
        - name: application-config
          configMap:
            name: demo-server-config-front
            items:
            - key: application.properties
              path: application.properties
        - name: spire-agent-socket
          hostPath:
           path: /mnt/spire/agent/socket