apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-server-ingress
spec:
  rules:
   - http:
      paths:
      - path: /
        backend:
          serviceName: demo-server-service-front
          servicePort: 443
