apiVersion: v1
kind: Service
metadata:
  name: demo-server-service-back
spec:
  type: NodePort
  ports:
    - name: http
      port: 444
      targetPort: 8443
      protocol: TCP
  selector:
    app: demo-server-back