apiVersion: v1
kind: Service
metadata:
  name: cloudid-proxy
spec:
  type: NodePort
  ports:
    - name: http
      port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: cloudid-proxy