apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: spire-server
  labels:
    app: spire-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-server
  template:
    metadata:
      labels:
        app: spire-server
    spec:
      containers:
        - name: spire-server
          imagePullPolicy: Never
          image: spire-server
          command:
            - /opt/spire/spire-server
            - run
            - -config
            - /spire/config/server.conf
          volumeMounts:
            - name: spire-config
              mountPath: /spire/config
              readOnly: true
            - name: spire-server-secrets
              mountPath: /spire/secrets
              readOnly: true
            - name: spire-ds
              mountPath: /spire/datastore
              readOnly: false
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 8081
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
      volumes:
        - name: spire-config
          configMap:
            name: spire-server-config
            items:
              - key: server.conf
                path: server.conf
        - name: spire-server-secrets
          secret:
            secretName: spire-server-secrets
        - name: spire-ds
          hostPath:
            path: /Volumes/Cloud-ID/codebase/spire-k8s/datastore